#!/opt/node/bin/node
// Quick wrapper script for running E4X in NodeJS
// Usage: node ./quick-run <file>
require.paths.push('./src');
require('./runtime/runtime').register('js');
var arg = process.argv[2];
if (!arg) {
  require('util').print('No input file specified!');
}
var fs = require('fs');
if (fs.statSync(arg)) {
  arg = fs.realpathSync(arg).replace(/\.[^.]+$/, '');
}
require(arg);
